[build]
    command="CI= npm run build"
    environment= {REACT_APP_RAILS_URL="https://shrouded-reef-53581.herokuapp.com/", REACT_APP_FRONT_URL="https://podtracker.netlify.app/"}

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200